# Generated by Django 5.2.15 on 2026-07-08 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engineer_id', models.IntegerField(help_text='References EngineerProfile ID')),
                ('service_request_id', models.IntegerField(help_text='References ServiceRequest ID in Customer Database')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
    ]
